package com.wni.demo.mapper;

import com.wni.demo.model.UserObject;
import com.wni.demo.model.UserObjectExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserObjectMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_object
     *
     * @mbg.generated
     */
    long countByExample(UserObjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_object
     *
     * @mbg.generated
     */
    int deleteByExample(UserObjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_object
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_object
     *
     * @mbg.generated
     */
    int insert(UserObject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_object
     *
     * @mbg.generated
     */
    int insertSelective(UserObject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_object
     *
     * @mbg.generated
     */
    List<UserObject> selectByExampleWithBLOBs(UserObjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_object
     *
     * @mbg.generated
     */
    List<UserObject> selectByExample(UserObjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_object
     *
     * @mbg.generated
     */
    UserObject selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_object
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") UserObject record, @Param("example") UserObjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_object
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("record") UserObject record, @Param("example") UserObjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_object
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") UserObject record, @Param("example") UserObjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_object
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(UserObject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_object
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(UserObject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_object
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(UserObject record);
}