package com.wni.demo.model;

import java.io.Serializable;
import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table user_object
 */
public class UserObject implements Serializable {
    /**
     * Database Column Remarks:
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_object.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_object.object_definition_id
     *
     * @mbg.generated
     */
    private Integer objectDefinitionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_object.code
     *
     * @mbg.generated
     */
    private String code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_object.user_login_id
     *
     * @mbg.generated
     */
    private String userLoginId;

    /**
     * Database Column Remarks:
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_object.user_phone_number
     *
     * @mbg.generated
     */
    private String userPhoneNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_object.user_name
     *
     * @mbg.generated
     */
    private String userName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_object.user_email
     *
     * @mbg.generated
     */
    private String userEmail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_object.user_gender
     *
     * @mbg.generated
     */
    private String userGender;

    /**
     * Database Column Remarks:
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_object.created_time
     *
     * @mbg.generated
     */
    private Date createdTime;

    /**
     * Database Column Remarks:
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_object.created_by
     *
     * @mbg.generated
     */
    private Integer createdBy;

    /**
     * Database Column Remarks:
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_object.last_modified_by
     *
     * @mbg.generated
     */
    private Integer lastModifiedBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_object.last_modified_time
     *
     * @mbg.generated
     */
    private Date lastModifiedTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_object.custom_field_1
     *
     * @mbg.generated
     */
    private String customField1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_object.custom_field_2
     *
     * @mbg.generated
     */
    private String customField2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_object.custom_field_3
     *
     * @mbg.generated
     */
    private String customField3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_object.custom_field_4
     *
     * @mbg.generated
     */
    private String customField4;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_object.custom_field_5
     *
     * @mbg.generated
     */
    private String customField5;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_object.custom_field_6
     *
     * @mbg.generated
     */
    private String customField6;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_object.custom_field_7
     *
     * @mbg.generated
     */
    private String customField7;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_object.custom_field_8
     *
     * @mbg.generated
     */
    private String customField8;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_object.custom_field_9
     *
     * @mbg.generated
     */
    private String customField9;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_object.custom_field_10
     *
     * @mbg.generated
     */
    private String customField10;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_object.custom_field_11
     *
     * @mbg.generated
     */
    private String customField11;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_object.custom_field_12
     *
     * @mbg.generated
     */
    private String customField12;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_object.custom_field_13
     *
     * @mbg.generated
     */
    private String customField13;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_object.custom_field_14
     *
     * @mbg.generated
     */
    private String customField14;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_object.custom_field_15
     *
     * @mbg.generated
     */
    private String customField15;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_object.custom_field_16
     *
     * @mbg.generated
     */
    private String customField16;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_object.custom_field_17
     *
     * @mbg.generated
     */
    private String customField17;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_object.custom_field_18
     *
     * @mbg.generated
     */
    private String customField18;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_object.custom_field_19
     *
     * @mbg.generated
     */
    private String customField19;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_object.custom_field_20
     *
     * @mbg.generated
     */
    private String customField20;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_object.custom_field_21
     *
     * @mbg.generated
     */
    private String customField21;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_object.custom_field_22
     *
     * @mbg.generated
     */
    private String customField22;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_object.custom_field_23
     *
     * @mbg.generated
     */
    private String customField23;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_object.custom_field_24
     *
     * @mbg.generated
     */
    private String customField24;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_object.custom_field_25
     *
     * @mbg.generated
     */
    private String customField25;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user_object
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_object.id
     *
     * @return the value of user_object.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_object.id
     *
     * @param id the value for user_object.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_object.object_definition_id
     *
     * @return the value of user_object.object_definition_id
     *
     * @mbg.generated
     */
    public Integer getObjectDefinitionId() {
        return objectDefinitionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_object.object_definition_id
     *
     * @param objectDefinitionId the value for user_object.object_definition_id
     *
     * @mbg.generated
     */
    public void setObjectDefinitionId(Integer objectDefinitionId) {
        this.objectDefinitionId = objectDefinitionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_object.code
     *
     * @return the value of user_object.code
     *
     * @mbg.generated
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_object.code
     *
     * @param code the value for user_object.code
     *
     * @mbg.generated
     */
    public void setCode(String code) {
        this.code = code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_object.user_login_id
     *
     * @return the value of user_object.user_login_id
     *
     * @mbg.generated
     */
    public String getUserLoginId() {
        return userLoginId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_object.user_login_id
     *
     * @param userLoginId the value for user_object.user_login_id
     *
     * @mbg.generated
     */
    public void setUserLoginId(String userLoginId) {
        this.userLoginId = userLoginId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_object.user_phone_number
     *
     * @return the value of user_object.user_phone_number
     *
     * @mbg.generated
     */
    public String getUserPhoneNumber() {
        return userPhoneNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_object.user_phone_number
     *
     * @param userPhoneNumber the value for user_object.user_phone_number
     *
     * @mbg.generated
     */
    public void setUserPhoneNumber(String userPhoneNumber) {
        this.userPhoneNumber = userPhoneNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_object.user_name
     *
     * @return the value of user_object.user_name
     *
     * @mbg.generated
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_object.user_name
     *
     * @param userName the value for user_object.user_name
     *
     * @mbg.generated
     */
    public void setUserName(String userName) {
        this.userName = userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_object.user_email
     *
     * @return the value of user_object.user_email
     *
     * @mbg.generated
     */
    public String getUserEmail() {
        return userEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_object.user_email
     *
     * @param userEmail the value for user_object.user_email
     *
     * @mbg.generated
     */
    public void setUserEmail(String userEmail) {
        this.userEmail = userEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_object.user_gender
     *
     * @return the value of user_object.user_gender
     *
     * @mbg.generated
     */
    public String getUserGender() {
        return userGender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_object.user_gender
     *
     * @param userGender the value for user_object.user_gender
     *
     * @mbg.generated
     */
    public void setUserGender(String userGender) {
        this.userGender = userGender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_object.created_time
     *
     * @return the value of user_object.created_time
     *
     * @mbg.generated
     */
    public Date getCreatedTime() {
        return createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_object.created_time
     *
     * @param createdTime the value for user_object.created_time
     *
     * @mbg.generated
     */
    public void setCreatedTime(Date createdTime) {
        this.createdTime = createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_object.created_by
     *
     * @return the value of user_object.created_by
     *
     * @mbg.generated
     */
    public Integer getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_object.created_by
     *
     * @param createdBy the value for user_object.created_by
     *
     * @mbg.generated
     */
    public void setCreatedBy(Integer createdBy) {
        this.createdBy = createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_object.last_modified_by
     *
     * @return the value of user_object.last_modified_by
     *
     * @mbg.generated
     */
    public Integer getLastModifiedBy() {
        return lastModifiedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_object.last_modified_by
     *
     * @param lastModifiedBy the value for user_object.last_modified_by
     *
     * @mbg.generated
     */
    public void setLastModifiedBy(Integer lastModifiedBy) {
        this.lastModifiedBy = lastModifiedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_object.last_modified_time
     *
     * @return the value of user_object.last_modified_time
     *
     * @mbg.generated
     */
    public Date getLastModifiedTime() {
        return lastModifiedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_object.last_modified_time
     *
     * @param lastModifiedTime the value for user_object.last_modified_time
     *
     * @mbg.generated
     */
    public void setLastModifiedTime(Date lastModifiedTime) {
        this.lastModifiedTime = lastModifiedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_object.custom_field_1
     *
     * @return the value of user_object.custom_field_1
     *
     * @mbg.generated
     */
    public String getCustomField1() {
        return customField1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_object.custom_field_1
     *
     * @param customField1 the value for user_object.custom_field_1
     *
     * @mbg.generated
     */
    public void setCustomField1(String customField1) {
        this.customField1 = customField1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_object.custom_field_2
     *
     * @return the value of user_object.custom_field_2
     *
     * @mbg.generated
     */
    public String getCustomField2() {
        return customField2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_object.custom_field_2
     *
     * @param customField2 the value for user_object.custom_field_2
     *
     * @mbg.generated
     */
    public void setCustomField2(String customField2) {
        this.customField2 = customField2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_object.custom_field_3
     *
     * @return the value of user_object.custom_field_3
     *
     * @mbg.generated
     */
    public String getCustomField3() {
        return customField3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_object.custom_field_3
     *
     * @param customField3 the value for user_object.custom_field_3
     *
     * @mbg.generated
     */
    public void setCustomField3(String customField3) {
        this.customField3 = customField3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_object.custom_field_4
     *
     * @return the value of user_object.custom_field_4
     *
     * @mbg.generated
     */
    public String getCustomField4() {
        return customField4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_object.custom_field_4
     *
     * @param customField4 the value for user_object.custom_field_4
     *
     * @mbg.generated
     */
    public void setCustomField4(String customField4) {
        this.customField4 = customField4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_object.custom_field_5
     *
     * @return the value of user_object.custom_field_5
     *
     * @mbg.generated
     */
    public String getCustomField5() {
        return customField5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_object.custom_field_5
     *
     * @param customField5 the value for user_object.custom_field_5
     *
     * @mbg.generated
     */
    public void setCustomField5(String customField5) {
        this.customField5 = customField5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_object.custom_field_6
     *
     * @return the value of user_object.custom_field_6
     *
     * @mbg.generated
     */
    public String getCustomField6() {
        return customField6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_object.custom_field_6
     *
     * @param customField6 the value for user_object.custom_field_6
     *
     * @mbg.generated
     */
    public void setCustomField6(String customField6) {
        this.customField6 = customField6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_object.custom_field_7
     *
     * @return the value of user_object.custom_field_7
     *
     * @mbg.generated
     */
    public String getCustomField7() {
        return customField7;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_object.custom_field_7
     *
     * @param customField7 the value for user_object.custom_field_7
     *
     * @mbg.generated
     */
    public void setCustomField7(String customField7) {
        this.customField7 = customField7;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_object.custom_field_8
     *
     * @return the value of user_object.custom_field_8
     *
     * @mbg.generated
     */
    public String getCustomField8() {
        return customField8;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_object.custom_field_8
     *
     * @param customField8 the value for user_object.custom_field_8
     *
     * @mbg.generated
     */
    public void setCustomField8(String customField8) {
        this.customField8 = customField8;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_object.custom_field_9
     *
     * @return the value of user_object.custom_field_9
     *
     * @mbg.generated
     */
    public String getCustomField9() {
        return customField9;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_object.custom_field_9
     *
     * @param customField9 the value for user_object.custom_field_9
     *
     * @mbg.generated
     */
    public void setCustomField9(String customField9) {
        this.customField9 = customField9;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_object.custom_field_10
     *
     * @return the value of user_object.custom_field_10
     *
     * @mbg.generated
     */
    public String getCustomField10() {
        return customField10;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_object.custom_field_10
     *
     * @param customField10 the value for user_object.custom_field_10
     *
     * @mbg.generated
     */
    public void setCustomField10(String customField10) {
        this.customField10 = customField10;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_object.custom_field_11
     *
     * @return the value of user_object.custom_field_11
     *
     * @mbg.generated
     */
    public String getCustomField11() {
        return customField11;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_object.custom_field_11
     *
     * @param customField11 the value for user_object.custom_field_11
     *
     * @mbg.generated
     */
    public void setCustomField11(String customField11) {
        this.customField11 = customField11;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_object.custom_field_12
     *
     * @return the value of user_object.custom_field_12
     *
     * @mbg.generated
     */
    public String getCustomField12() {
        return customField12;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_object.custom_field_12
     *
     * @param customField12 the value for user_object.custom_field_12
     *
     * @mbg.generated
     */
    public void setCustomField12(String customField12) {
        this.customField12 = customField12;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_object.custom_field_13
     *
     * @return the value of user_object.custom_field_13
     *
     * @mbg.generated
     */
    public String getCustomField13() {
        return customField13;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_object.custom_field_13
     *
     * @param customField13 the value for user_object.custom_field_13
     *
     * @mbg.generated
     */
    public void setCustomField13(String customField13) {
        this.customField13 = customField13;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_object.custom_field_14
     *
     * @return the value of user_object.custom_field_14
     *
     * @mbg.generated
     */
    public String getCustomField14() {
        return customField14;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_object.custom_field_14
     *
     * @param customField14 the value for user_object.custom_field_14
     *
     * @mbg.generated
     */
    public void setCustomField14(String customField14) {
        this.customField14 = customField14;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_object.custom_field_15
     *
     * @return the value of user_object.custom_field_15
     *
     * @mbg.generated
     */
    public String getCustomField15() {
        return customField15;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_object.custom_field_15
     *
     * @param customField15 the value for user_object.custom_field_15
     *
     * @mbg.generated
     */
    public void setCustomField15(String customField15) {
        this.customField15 = customField15;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_object.custom_field_16
     *
     * @return the value of user_object.custom_field_16
     *
     * @mbg.generated
     */
    public String getCustomField16() {
        return customField16;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_object.custom_field_16
     *
     * @param customField16 the value for user_object.custom_field_16
     *
     * @mbg.generated
     */
    public void setCustomField16(String customField16) {
        this.customField16 = customField16;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_object.custom_field_17
     *
     * @return the value of user_object.custom_field_17
     *
     * @mbg.generated
     */
    public String getCustomField17() {
        return customField17;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_object.custom_field_17
     *
     * @param customField17 the value for user_object.custom_field_17
     *
     * @mbg.generated
     */
    public void setCustomField17(String customField17) {
        this.customField17 = customField17;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_object.custom_field_18
     *
     * @return the value of user_object.custom_field_18
     *
     * @mbg.generated
     */
    public String getCustomField18() {
        return customField18;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_object.custom_field_18
     *
     * @param customField18 the value for user_object.custom_field_18
     *
     * @mbg.generated
     */
    public void setCustomField18(String customField18) {
        this.customField18 = customField18;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_object.custom_field_19
     *
     * @return the value of user_object.custom_field_19
     *
     * @mbg.generated
     */
    public String getCustomField19() {
        return customField19;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_object.custom_field_19
     *
     * @param customField19 the value for user_object.custom_field_19
     *
     * @mbg.generated
     */
    public void setCustomField19(String customField19) {
        this.customField19 = customField19;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_object.custom_field_20
     *
     * @return the value of user_object.custom_field_20
     *
     * @mbg.generated
     */
    public String getCustomField20() {
        return customField20;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_object.custom_field_20
     *
     * @param customField20 the value for user_object.custom_field_20
     *
     * @mbg.generated
     */
    public void setCustomField20(String customField20) {
        this.customField20 = customField20;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_object.custom_field_21
     *
     * @return the value of user_object.custom_field_21
     *
     * @mbg.generated
     */
    public String getCustomField21() {
        return customField21;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_object.custom_field_21
     *
     * @param customField21 the value for user_object.custom_field_21
     *
     * @mbg.generated
     */
    public void setCustomField21(String customField21) {
        this.customField21 = customField21;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_object.custom_field_22
     *
     * @return the value of user_object.custom_field_22
     *
     * @mbg.generated
     */
    public String getCustomField22() {
        return customField22;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_object.custom_field_22
     *
     * @param customField22 the value for user_object.custom_field_22
     *
     * @mbg.generated
     */
    public void setCustomField22(String customField22) {
        this.customField22 = customField22;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_object.custom_field_23
     *
     * @return the value of user_object.custom_field_23
     *
     * @mbg.generated
     */
    public String getCustomField23() {
        return customField23;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_object.custom_field_23
     *
     * @param customField23 the value for user_object.custom_field_23
     *
     * @mbg.generated
     */
    public void setCustomField23(String customField23) {
        this.customField23 = customField23;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_object.custom_field_24
     *
     * @return the value of user_object.custom_field_24
     *
     * @mbg.generated
     */
    public String getCustomField24() {
        return customField24;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_object.custom_field_24
     *
     * @param customField24 the value for user_object.custom_field_24
     *
     * @mbg.generated
     */
    public void setCustomField24(String customField24) {
        this.customField24 = customField24;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_object.custom_field_25
     *
     * @return the value of user_object.custom_field_25
     *
     * @mbg.generated
     */
    public String getCustomField25() {
        return customField25;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_object.custom_field_25
     *
     * @param customField25 the value for user_object.custom_field_25
     *
     * @mbg.generated
     */
    public void setCustomField25(String customField25) {
        this.customField25 = customField25;
    }
}
